CREATE TABLE agendamentos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cliente_id BIGINT UNSIGNED NOT NULL,
  barbeiro_id BIGINT UNSIGNED NOT NULL,
  servico_id BIGINT UNSIGNED NOT NULL,
  criado_por BIGINT UNSIGNED NOT NULL,
  origem VARCHAR(20) NOT NULL,
  inicio_em DATETIME(6) NOT NULL,
  fim_em DATETIME(6) NOT NULL,
  preco DECIMAL(10,2) NOT NULL,
  duracao_minutos SMALLINT UNSIGNED NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pendente',
  observacoes_cliente TEXT NULL,
  observacoes_internas TEXT NULL,
  cancelado_por BIGINT UNSIGNED NULL,
  motivo_cancelamento VARCHAR(500) NULL,
  criado_em DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  atualizado_em DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  concluido_em DATETIME(6) NULL,
  cancelado_em DATETIME(6) NULL,
  PRIMARY KEY (id),
  CONSTRAINT chk_agendamentos_origem CHECK (origem IN ('cliente', 'admin', 'sistema')),
  CONSTRAINT chk_agendamentos_status CHECK (status IN ('pendente', 'confirmado', 'em_atendimento', 'concluido', 'cancelado', 'ausente')),
  CONSTRAINT chk_agendamentos_periodo CHECK (fim_em > inicio_em),
  CONSTRAINT chk_agendamentos_preco CHECK (preco >= 0),
  CONSTRAINT chk_agendamentos_duracao CHECK (duracao_minutos > 0),
  CONSTRAINT chk_agendamentos_conclusao CHECK ((status = 'concluido' AND concluido_em IS NOT NULL) OR (status <> 'concluido' AND concluido_em IS NULL)),
  CONSTRAINT chk_agendamentos_cancelamento CHECK ((status = 'cancelado' AND cancelado_em IS NOT NULL AND cancelado_por IS NOT NULL) OR (status <> 'cancelado' AND cancelado_em IS NULL AND cancelado_por IS NULL)),
  INDEX idx_agendamentos_barbeiro_agenda (barbeiro_id, inicio_em, fim_em, status),
  INDEX idx_agendamentos_cliente_agenda (cliente_id, inicio_em, status),
  INDEX idx_agendamentos_status_inicio (status, inicio_em),
  INDEX idx_agendamentos_servico_inicio (servico_id, inicio_em),
  INDEX idx_agendamentos_criado_por (criado_por),
  CONSTRAINT fk_agendamentos_cliente FOREIGN KEY (cliente_id) REFERENCES usuarios (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_agendamentos_barbeiro FOREIGN KEY (barbeiro_id) REFERENCES barbeiros (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_agendamentos_servico FOREIGN KEY (servico_id) REFERENCES servicos (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_agendamentos_criador FOREIGN KEY (criado_por) REFERENCES usuarios (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_agendamentos_cancelador FOREIGN KEY (cancelado_por) REFERENCES usuarios (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
