export const TRANSIENT_MYSQL_ERROR_CODES = Object.freeze([
  'ER_LOCK_DEADLOCK',
  'ER_LOCK_WAIT_TIMEOUT',
]);
export const TRANSACTION_MAX_ATTEMPTS = 3;
export const TRANSACTION_RETRY_INITIAL_DELAY_MS = 25;
export const TRANSACTION_RETRY_MAX_DELAY_MS = 100;
